{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "231e2939-09cf-4fb7-84d1-82181d672a82",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "import altair as alt\n",
    "import numpy as np\n",
    "import plotly.express as px\n",
    "from sklearn.linear_model import LinearRegression\n",
    "from sklearn.cluster import KMeans"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "7db43333-5b19-40bd-91c2-2ecd29c9398c",
   "metadata": {},
   "outputs": [],
   "source": [
    "df = pd.read_csv('job_salary_prediction_dataset.csv')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "1eda0995-4b97-46e3-aa14-e9bdf514c1aa",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<class 'pandas.core.frame.DataFrame'>\n",
      "RangeIndex: 250000 entries, 0 to 249999\n",
      "Data columns (total 10 columns):\n",
      " #   Column            Non-Null Count   Dtype \n",
      "---  ------            --------------   ----- \n",
      " 0   job_title         250000 non-null  object\n",
      " 1   experience_years  250000 non-null  int64 \n",
      " 2   education_level   250000 non-null  object\n",
      " 3   skills_count      250000 non-null  int64 \n",
      " 4   industry          250000 non-null  object\n",
      " 5   company_size      250000 non-null  object\n",
      " 6   location          250000 non-null  object\n",
      " 7   remote_work       250000 non-null  object\n",
      " 8   certifications    250000 non-null  int64 \n",
      " 9   salary            250000 non-null  int64 \n",
      "dtypes: int64(4), object(6)\n",
      "memory usage: 19.1+ MB\n"
     ]
    }
   ],
   "source": [
    "df.info()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "174ccf43-52f6-449d-8b1c-4a2908281930",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>experience_years</th>\n",
       "      <th>skills_count</th>\n",
       "      <th>certifications</th>\n",
       "      <th>salary</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>count</th>\n",
       "      <td>250000.000000</td>\n",
       "      <td>250000.000000</td>\n",
       "      <td>250000.000000</td>\n",
       "      <td>250000.000000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>mean</th>\n",
       "      <td>10.005408</td>\n",
       "      <td>9.997812</td>\n",
       "      <td>2.491928</td>\n",
       "      <td>145718.080524</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>std</th>\n",
       "      <td>6.060602</td>\n",
       "      <td>5.479288</td>\n",
       "      <td>1.706475</td>\n",
       "      <td>37407.952729</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>min</th>\n",
       "      <td>0.000000</td>\n",
       "      <td>1.000000</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>31867.000000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>25%</th>\n",
       "      <td>5.000000</td>\n",
       "      <td>5.000000</td>\n",
       "      <td>1.000000</td>\n",
       "      <td>119358.000000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>50%</th>\n",
       "      <td>10.000000</td>\n",
       "      <td>10.000000</td>\n",
       "      <td>2.000000</td>\n",
       "      <td>143453.000000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>75%</th>\n",
       "      <td>15.000000</td>\n",
       "      <td>15.000000</td>\n",
       "      <td>4.000000</td>\n",
       "      <td>169492.000000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>max</th>\n",
       "      <td>20.000000</td>\n",
       "      <td>19.000000</td>\n",
       "      <td>5.000000</td>\n",
       "      <td>333046.000000</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "       experience_years   skills_count  certifications         salary\n",
       "count     250000.000000  250000.000000   250000.000000  250000.000000\n",
       "mean          10.005408       9.997812        2.491928  145718.080524\n",
       "std            6.060602       5.479288        1.706475   37407.952729\n",
       "min            0.000000       1.000000        0.000000   31867.000000\n",
       "25%            5.000000       5.000000        1.000000  119358.000000\n",
       "50%           10.000000      10.000000        2.000000  143453.000000\n",
       "75%           15.000000      15.000000        4.000000  169492.000000\n",
       "max           20.000000      19.000000        5.000000  333046.000000"
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df.describe()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "2d3584a8-94b6-44e2-b350-7a2f7b30f3c9",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "job_title\n",
      "job_title\n",
      "False    250000\n",
      "Name: count, dtype: int64\n",
      "\n",
      "experience_years\n",
      "experience_years\n",
      "False    250000\n",
      "Name: count, dtype: int64\n",
      "\n",
      "education_level\n",
      "education_level\n",
      "False    250000\n",
      "Name: count, dtype: int64\n",
      "\n",
      "skills_count\n",
      "skills_count\n",
      "False    250000\n",
      "Name: count, dtype: int64\n",
      "\n",
      "industry\n",
      "industry\n",
      "False    250000\n",
      "Name: count, dtype: int64\n",
      "\n",
      "company_size\n",
      "company_size\n",
      "False    250000\n",
      "Name: count, dtype: int64\n",
      "\n",
      "location\n",
      "location\n",
      "False    250000\n",
      "Name: count, dtype: int64\n",
      "\n",
      "remote_work\n",
      "remote_work\n",
      "False    250000\n",
      "Name: count, dtype: int64\n",
      "\n",
      "certifications\n",
      "certifications\n",
      "False    250000\n",
      "Name: count, dtype: int64\n",
      "\n",
      "salary\n",
      "salary\n",
      "False    250000\n",
      "Name: count, dtype: int64\n",
      "\n"
     ]
    }
   ],
   "source": [
    "missing_data = df.isnull()\n",
    "for column in missing_data.columns.values.tolist():\n",
    "    print(column)\n",
    "    print (missing_data[column].value_counts())\n",
    "    print(\"\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "d4755a50-f2c0-4cc2-9ae0-8028bb691776",
   "metadata": {},
   "outputs": [],
   "source": [
    "st.set_page_config(\n",
    "    page_title=\"Зарплатний дашборд\",\n",
    "    page_icon=\"📊\",\n",
    "    layout=\"wide\",\n",
    "    initial_sidebar_state=\"expanded\",\n",
    "    menu_items={\n",
    "        'Get Help': 'https://docs.streamlit.io/',\n",
    "        'Report a bug': 'https://github.com/streamlit/streamlit/issues',\n",
    "        'About': 'Інтерактивна панель для аналізу рівню зарплат'\n",
    "    }\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "24a5546f-e4b3-4517-8c42-96e2b4522f36",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "DeltaGenerator(_root_container=1, _parent=DeltaGenerator())"
      ]
     },
     "execution_count": 10,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Бічна панель / SIDEBAR\n",
    "st.sidebar.title(\"Панель фільтрації\")\n",
    "\n",
    "# Фільтри\n",
    "selected_year = st.sidebar.selectbox(\"Досвід в роках\", sorted(df[\"experience_years\"].unique()))\n",
    "selected_region = st.sidebar.multiselect(\"Регіон\", df[\"location\"].unique(), default=df[\"location\"].unique())\n",
    "selected_industry = st.sidebar.multiselect(\"Галузь\", df[\"industry\"].unique(), default=df[\"industry\"].unique())\n",
    "selected_scenario = st.sidebar.radio(\"Сертифікація\", df[\"certifications\"].unique())\n",
    "\n",
    "selected_max_adbudget = st.sidebar.slider(\n",
    "    \"Максимальна заробітна плата\",\n",
    "    min_value=int(df[\"salary\"].min()),\n",
    "    max_value=int(df[\"salary\"].max()),\n",
    "    value=int(df[\"salary\"].max()),\n",
    "    step=1000\n",
    ")\n",
    "\n",
    "# Чекбокси для відображення\n",
    "show_map = st.sidebar.checkbox(\"Показати Зарплата vs Досвід\")\n",
    "\n",
    "# Перемикач графіків\n",
    "chart_option = st.sidebar.radio(\n",
    "    \"📈 Оберіть графік для перегляду:\",\n",
    "    [\n",
    "        \"Доходи на клієнта vs Витрати\",\n",
    "        \"Boxplot прибутку по галузях\",\n",
    "        \"Scatter: Прибуток vs Інвестиції\",\n",
    "        \"Гістограма конверсії по галузях\",\n",
    "        \"Теплова карта кореляцій\",\n",
    "        \"Кластеризація компаній (KMeans)\"\n",
    "    ]\n",
    ")\n",
    "\n",
    "# Інформаційний блок\n",
    "st.sidebar.markdown(\"---\")\n",
    "st.sidebar.markdown(\" **Інструкція**: \\nФільтруйте дані за параметрами і переглядайте графіки та таблиці на панелі праворуч.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "b76102dd-068e-4850-aafb-35001c5ab3e7",
   "metadata": {},
   "outputs": [],
   "source": [
    "df_filtered = df[\n",
    "    (df[\"experience_years\"] == selected_year) &\n",
    "    (df[\"location\"].isin(selected_region)) &\n",
    "    (df[\"industry\"].isin(selected_industry)) &\n",
    "    (df[\"certifications\"] == selected_scenario) &\n",
    "    (df[\"salary\"] <= selected_max_adbudget)\n",
    "]\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "86bcea81-ad4f-4a39-a7fc-0ae0fd48863b",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Блок регресії\n",
    "st.sidebar.markdown(\"Побудова регресії\")\n",
    "numeric_columns = df_filtered.select_dtypes(include=np.number).columns.tolist()\n",
    "\n",
    "reg_x = st.sidebar.selectbox(\"Оберіть змінну X\", numeric_columns, index=0)\n",
    "reg_y = st.sidebar.selectbox(\"Оберіть змінну Y\", numeric_columns, index=1)\n",
    "show_regression = st.sidebar.checkbox(\"Показати регресійну модель\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "0f67fc7e-2214-4333-a4b0-ce0b450efc24",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Основна панель\n",
    "st.title(\"Зарплатний дашборд\")\n",
    "st.subheader(f\"🔍 Відфільтровано {df_filtered.shape[0]} зарплат\")\n",
    "\n",
    "# Кнопка завантаження CSV\n",
    "csv = df_filtered.to_csv(index=False).encode(\"utf-8\")\n",
    "st.download_button(\n",
    "    label=\"⬇️ Завантажити CSV\",\n",
    "    data=csv,\n",
    "    file_name=\"filtered_salary.csv\",\n",
    "    mime=\"text/csv\"\n",
    ")\n",
    "\n",
    "# Інтерактивна таблиця результатів\n",
    "st.subheader(\"Оберіть, які стовпці таблиці відображати\")\n",
    "\n",
    "all_columns = df_filtered.columns.tolist()\n",
    "default_columns = [\"job_title\", \"experience_years\", \"industry\", \"location\", \"salary\"]\n",
    "\n",
    "selected_columns = st.multiselect(\n",
    "    \"Оберіть стовпці для перегляду\",\n",
    "    options=all_columns,\n",
    "    default=[col for col in default_columns if col in all_columns]\n",
    ")\n",
    "\n",
    "if selected_columns:\n",
    "    st.dataframe(df_filtered[selected_columns])\n",
    "else:\n",
    "    st.info(\"Оберіть хоча б один стовпець, щоб побачити таблицю.\")\n",
    "\n",
    "if chart_option == \"Зарплата vs Досвід\":\n",
    "    st.subheader(\"📊 Зарплата vs Досвід\")\n",
    "    chart = alt.Chart(df_filtered).mark_circle(size=60).encode(\n",
    "        x=\"experience_years:Q\",\n",
    "        y=\"salary:Q\",\n",
    "        color=\"industry:N\",\n",
    "        tooltip=[\"job_title\", \"experience_years\", \"salary\", \"industry\"]\n",
    "    ).interactive().properties(title=\"Зарплата vs Досвід\")\n",
    "    st.altair_chart(chart, use_container_width=True)\n",
    "\n",
    "elif chart_option == \"Boxplot зарплати по галузях\":\n",
    "    st.subheader(\"📊 Boxplot зарплати по галузях\")\n",
    "    fig, ax = plt.subplots(figsize=(10, 5))\n",
    "    sns.boxplot(data=df_filtered, x=\"industry\", y=\"salary\", ax=ax)\n",
    "    ax.set_title(\"Розподіл зарплат по галузях\")\n",
    "    st.pyplot(fig)\n",
    "\n",
    "elif chart_option == \"Scatter: Зарплата vs Кількість скілів\":\n",
    "    st.subheader(\"📊 Scatter: Зарплата vs Кількість скілів\")\n",
    "    chart = alt.Chart(df_filtered).mark_circle(size=60).encode(\n",
    "        x=\"skills_count:Q\",\n",
    "        y=\"salary:Q\",\n",
    "        color=\"industry:N\",\n",
    "        tooltip=[\"job_title\", \"skills_count\", \"salary\"]\n",
    "    ).interactive().properties(title=\"Зарплата vs Кількість скілів\")\n",
    "    st.altair_chart(chart, use_container_width=True)\n",
    "\n",
    "elif chart_option == \"Гістограма сертифікацій по галузях\":\n",
    "    st.subheader(\"📊 Гістограма сертифікацій по галузях\")\n",
    "    fig, ax = plt.subplots(figsize=(10, 5))\n",
    "    sns.barplot(\n",
    "        data=df_filtered,\n",
    "        x=\"industry\",\n",
    "        y=\"certifications\",\n",
    "        estimator=\"mean\",\n",
    "        ax=ax\n",
    "    )\n",
    "    ax.set_title(\"Середня кількість сертифікацій по галузях\")\n",
    "    st.pyplot(fig)\n",
    "\n",
    "elif chart_option == \"Теплова карта кореляцій\":\n",
    "    st.subheader(\"📊 Теплова карта кореляцій\")\n",
    "    numeric_cols = df_filtered.select_dtypes(include=[np.number])\n",
    "    corr = numeric_cols.corr()\n",
    "    fig, ax = plt.subplots(figsize=(10, 6))\n",
    "    sns.heatmap(corr, annot=True, cmap=\"coolwarm\", fmt=\".2f\", ax=ax)\n",
    "    ax.set_title(\"Кореляційна матриця числових показників\")\n",
    "    st.pyplot(fig)\n",
    "\n",
    "elif chart_option == \"Кластеризація кандидатів (KMeans)\":\n",
    "    st.subheader(\"📊 Кластеризація кандидатів за зарплатою та досвідом\")\n",
    "    cluster_data = df_filtered[[\"salary\", \"experience_years\"]].dropna().copy()\n",
    "\n",
    "    if cluster_data.shape[0] >= 3:\n",
    "        kmeans = KMeans(n_clusters=3, random_state=0)\n",
    "        cluster_data[\"Cluster\"] = kmeans.fit_predict(cluster_data)\n",
    "\n",
    "        chart = alt.Chart(cluster_data).mark_circle(size=60).encode(\n",
    "            x=\"experience_years:Q\",\n",
    "            y=\"salary:Q\",\n",
    "            color=\"Cluster:N\",\n",
    "            tooltip=[\"salary\", \"experience_years\", \"Cluster\"]\n",
    "        ).interactive().properties(title=\"Кластеризація за зарплатою та досвідом\")\n",
    "        st.altair_chart(chart, use_container_width=True)\n",
    "    else:\n",
    "        st.warning(\"Недостатньо даних для кластеризації (потрібно ≥ 3 рядки).\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5e7b3899-89fc-4b7b-837f-d1baeb7fb17d",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
