{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {
    "id": "GzG85jXXkg_S"
   },
   "source": [
    "<center><font size=\"6\"><b>Комп'ютерний практикум 6.\n",
    "\n",
    "<center><b> Створення дашборду за допомогою Streamlit </font>\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "id": "nkSp72R80cGt"
   },
   "source": [
    "\n",
    "<center><img src=\"https://www.dataquest.io/wp-content/uploads/2024/02/Why-Should-You-Learn-Streamlit-in-2024.png.webp\" width=\"600\"></center>\n",
    "\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "id": "Bg_hTWNExzvt"
   },
   "source": [
    "# __Streamlit__\n",
    "__Streamlit__ - це безкоштовна і відкрита бібліотека Python для створення і розповсюдження веб-додатків для машинного навчання та аналізу даних. Streamlit дає  змогу перетворити свої скрипти з даними на інтерактивні веб-додатки за кілька хвилин.\n",
    "\n",
    "### Можливості Streamlit:\n",
    "\n",
    "*   Створити привабливий і функціональний інтерфейс для алгоритмів, моделей, візуалізацій, дашбордів та інших продуктів з даними.\n",
    "*   Робити експерименти та ітерації з даними і кодом, використовуючи  простий API, який автоматично оновлює ваш застосунок під час збереження вихідного файлу.\n",
    "*   Додавати взаємодію з вашими даними і додатком, використовуючи різні віджети, такі як слайдери, кнопки, чекбокси, радіокнопки, випадаючі списки та інші.\n",
    "* Ділитися своїми додатками з колегами, клієнтами, спільнотою або всім світом, використовуючи  платформу Community Cloud або свій власний сервер.\n",
    "\n",
    "\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "id": "S6rL2H1vAgNf"
   },
   "outputs": [],
   "source": [
    "# Завантажимо Streamlit (не додавати в .py файл додатку)\n",
    "!pip install streamlit"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "id": "hwSuTm52_5hY"
   },
   "source": [
    "**Python-бібліотеки**, які можуть використовуються у створеному Streamlit-додатку:\n",
    "\n",
    "| Бібліотека            | Призначення                                                                 |\n",
    "|-----------------------|------------------------------------------------------------------------------|\n",
    "| **`streamlit`**       | Основна бібліотека для створення **інтерактивного вебдодатку**. Створює інтерфейс, фільтри, графіки, карту. |\n",
    "| **`pandas`**          |  Робота з табличними даними (DataFrame) — читання, фільтрація, обчислення нових змінних. |\n",
    "| **`matplotlib.pyplot`** |  Побудова класичних графіків (гістограми, scatter, лінійні графіки, heatmap). |\n",
    "| **`seaborn`**         |  Стилізовані графіки на основі matplotlib — barplot, boxplot, heatmap з анотаціями. |\n",
    "|**`altair`**|Декларативна система побудови інтерактивних графіків, яка працює особливо добре в Streamlit. Підходить для побудови інтерактивних діаграм, фільтрації та дослідження взаємозв’язків у даних|\n",
    "| **`numpy`**           |  Математичні операції, генерація випадкових чисел для симуляцій (Монте-Карло). |\n",
    "| **`plotly.express`**  |  Інтерактивні графіки: scatter з підказками, інтерактивні осі, кольори, розміри. |\n",
    "| **`sklearn.linear_model`** | Лінійна регресія — побудова моделі для оцінки залежності ROI від AdBudget. |\n",
    "| **`sklearn.cluster`** |  Кластеризація (алгоритм KMeans) для групування компаній за економічними показниками. |\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "id": "w7Ntq5ZW3DAp"
   },
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "import altair as alt\n",
    "import numpy as np\n",
    "import plotly.express as px\n",
    "from sklearn.linear_model import LinearRegression\n",
    "from sklearn.cluster import KMeans"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "id": "Br-KK_Sw6pYm"
   },
   "source": [
    "__Завантажимо дані__\n",
    "\n",
    "Маємо датасет **`streamlit_dataset.xlsx`**:\n",
    "\n",
    "| Назва змінної        | Тип             | Опис |\n",
    "|----------------------|------------------|------|\n",
    "| **Company**          | `str`            | Назва компанії (`Company_1`, `Company_2`, ...). Унікальний ідентифікатор суб’єкта аналізу. |\n",
    "| **Year**             | `int`            | Рік, за який наведені фінансові показники (2022, 2023, 2024). |\n",
    "| **Region**           | `str`            | Географічний регіон діяльності компанії: `North`, `South`, `East`, `West`. |\n",
    "| **Industry**         | `str`            | Галузь економіки: `Finance`, `Tech`, `Retail`, `Manufacturing`. |\n",
    "| **Revenue**          | `int`            | Загальний дохід компанії за відповідний рік. |\n",
    "| **Expenses**         | `int`            | Загальні витрати компанії за відповідний рік. |\n",
    "| **Investment**       | `int`            | Обсяг інвестицій у розвиток або рекламу. |\n",
    "| **Customers**        | `int`            | Кількість клієнтів, яких обслуговувала компанія. |\n",
    "| **ConversionRate**   | `float`          | Частка клієнтів, які здійснили цільову дію (наприклад, купівлю). Є пропущені значення. |\n",
    "| **Profit**           | `int`            | Прибуток компанії = Revenue − Expenses. |\n",
    "| **ROI**              | `float`          | Рентабельність інвестицій = Profit / Investment. |\n",
    "| **RevenuePerCustomer** | `float`        | Дохід на одного клієнта = Revenue / Customers. |\n",
    "| **Latitude**         | `float`          | Географічна широта для відображення компанії на мапі. |\n",
    "| **Longitude**        | `float`          | Географічна довгота для мапи. |\n",
    "| **Scenario**         | `str`            | Бізнес-сценарій, в рамках якого оцінюються показники: `Baseline`, `Optimistic`, `Pessimistic`. |\n",
    "| **MarketGrowth**     | `float`          | Темп зростання ринку (в %) — умовна макроекономічна змінна для моделювання. |\n",
    "| **AdBudget**         | `float`          | Бюджет на рекламу або маркетинг. Використовується для аналізу ефективності. |\n",
    "\n",
    "\n",
    "\n",
    "___Застосування змінних:___\n",
    "\n",
    "- **Кількісні змінні** (`Revenue`, `Expenses`, `Profit`, `ROI`, `Customers`, `AdBudget`) — підходять для графіків, регресій, кластеризацій.\n",
    "- **Категоріальні змінні** (`Region`, `Industry`, `Scenario`) — для групування, фільтрації, аналізу розподілів.\n",
    "- **Просторові змінні** (`Latitude`, `Longitude`) — для інтерактивної карти.\n",
    "- **ConversionRate** — підходить для демонстрації роботи з пропущеними даними.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {
    "id": "jMCCFys3x6K-"
   },
   "outputs": [],
   "source": [
    "df = pd.read_csv('streamlit_dataset.csv')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "id": "E1HNr8pEBLpI"
   },
   "source": [
    "## __Розвідувальний аналіз даних (EDA)__\n",
    "Для якісної роботи з даними та їх представленням, використанням для моделювання, їх необхідно попередньо опрацювати. Тому етап препроцесінгу та розвідувального аналізу є ключовим в підготовці даних."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {
    "id": "gAD0FTB13udb"
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<class 'pandas.core.frame.DataFrame'>\n",
      "RangeIndex: 100 entries, 0 to 99\n",
      "Data columns (total 17 columns):\n",
      " #   Column              Non-Null Count  Dtype  \n",
      "---  ------              --------------  -----  \n",
      " 0   Company             100 non-null    object \n",
      " 1   Year                100 non-null    int64  \n",
      " 2   Region              100 non-null    object \n",
      " 3   Industry            100 non-null    object \n",
      " 4   Revenue             100 non-null    int64  \n",
      " 5   Expenses            100 non-null    int64  \n",
      " 6   Investment          100 non-null    int64  \n",
      " 7   Customers           100 non-null    int64  \n",
      " 8   ConversionRate      90 non-null     float64\n",
      " 9   Profit              100 non-null    int64  \n",
      " 10  ROI                 100 non-null    float64\n",
      " 11  RevenuePerCustomer  100 non-null    float64\n",
      " 12  Latitude            100 non-null    float64\n",
      " 13  Longitude           100 non-null    float64\n",
      " 14  Scenario            100 non-null    object \n",
      " 15  MarketGrowth        100 non-null    float64\n",
      " 16  AdBudget            100 non-null    float64\n",
      "dtypes: float64(7), int64(6), object(4)\n",
      "memory usage: 13.4+ KB\n"
     ]
    }
   ],
   "source": [
    "df.info()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {
    "id": "WGwtma2B460L"
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Year</th>\n",
       "      <th>Revenue</th>\n",
       "      <th>Expenses</th>\n",
       "      <th>Investment</th>\n",
       "      <th>Customers</th>\n",
       "      <th>ConversionRate</th>\n",
       "      <th>Profit</th>\n",
       "      <th>ROI</th>\n",
       "      <th>RevenuePerCustomer</th>\n",
       "      <th>Latitude</th>\n",
       "      <th>Longitude</th>\n",
       "      <th>MarketGrowth</th>\n",
       "      <th>AdBudget</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>count</th>\n",
       "      <td>100.000000</td>\n",
       "      <td>100.000000</td>\n",
       "      <td>100.000000</td>\n",
       "      <td>100.000000</td>\n",
       "      <td>100.000000</td>\n",
       "      <td>90.000000</td>\n",
       "      <td>100.000000</td>\n",
       "      <td>100.000000</td>\n",
       "      <td>100.000000</td>\n",
       "      <td>100.000000</td>\n",
       "      <td>100.000000</td>\n",
       "      <td>100.000000</td>\n",
       "      <td>100.000000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>mean</th>\n",
       "      <td>2022.980000</td>\n",
       "      <td>208287.300000</td>\n",
       "      <td>159062.100000</td>\n",
       "      <td>52077.030000</td>\n",
       "      <td>1001.370000</td>\n",
       "      <td>0.106458</td>\n",
       "      <td>49225.200000</td>\n",
       "      <td>1.061028</td>\n",
       "      <td>208.280924</td>\n",
       "      <td>49.384300</td>\n",
       "      <td>30.876300</td>\n",
       "      <td>4.995655</td>\n",
       "      <td>29534.088215</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>std</th>\n",
       "      <td>0.803779</td>\n",
       "      <td>45363.869918</td>\n",
       "      <td>36615.183976</td>\n",
       "      <td>14959.048863</td>\n",
       "      <td>30.968102</td>\n",
       "      <td>0.055854</td>\n",
       "      <td>26484.609076</td>\n",
       "      <td>0.805744</td>\n",
       "      <td>46.171606</td>\n",
       "      <td>1.430864</td>\n",
       "      <td>4.663345</td>\n",
       "      <td>1.665239</td>\n",
       "      <td>5252.362788</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>min</th>\n",
       "      <td>2022.000000</td>\n",
       "      <td>110575.000000</td>\n",
       "      <td>85825.000000</td>\n",
       "      <td>13216.000000</td>\n",
       "      <td>919.000000</td>\n",
       "      <td>0.010880</td>\n",
       "      <td>9157.000000</td>\n",
       "      <td>0.130130</td>\n",
       "      <td>105.510496</td>\n",
       "      <td>46.480000</td>\n",
       "      <td>24.020000</td>\n",
       "      <td>1.315110</td>\n",
       "      <td>13179.522368</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>25%</th>\n",
       "      <td>2022.000000</td>\n",
       "      <td>176619.750000</td>\n",
       "      <td>131637.500000</td>\n",
       "      <td>43515.000000</td>\n",
       "      <td>979.000000</td>\n",
       "      <td>0.054472</td>\n",
       "      <td>27930.250000</td>\n",
       "      <td>0.595550</td>\n",
       "      <td>176.025604</td>\n",
       "      <td>49.830000</td>\n",
       "      <td>28.895000</td>\n",
       "      <td>3.938343</td>\n",
       "      <td>26088.799167</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>50%</th>\n",
       "      <td>2023.000000</td>\n",
       "      <td>207772.000000</td>\n",
       "      <td>160973.500000</td>\n",
       "      <td>53473.500000</td>\n",
       "      <td>1000.000000</td>\n",
       "      <td>0.105768</td>\n",
       "      <td>45020.500000</td>\n",
       "      <td>0.859758</td>\n",
       "      <td>202.093757</td>\n",
       "      <td>49.990000</td>\n",
       "      <td>30.730000</td>\n",
       "      <td>4.921285</td>\n",
       "      <td>29232.128695</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>75%</th>\n",
       "      <td>2024.000000</td>\n",
       "      <td>243601.750000</td>\n",
       "      <td>185880.500000</td>\n",
       "      <td>62878.750000</td>\n",
       "      <td>1024.000000</td>\n",
       "      <td>0.152207</td>\n",
       "      <td>66727.750000</td>\n",
       "      <td>1.293277</td>\n",
       "      <td>242.041613</td>\n",
       "      <td>49.990000</td>\n",
       "      <td>36.230000</td>\n",
       "      <td>6.156511</td>\n",
       "      <td>33816.318723</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>max</th>\n",
       "      <td>2024.000000</td>\n",
       "      <td>336721.000000</td>\n",
       "      <td>257380.000000</td>\n",
       "      <td>84136.000000</td>\n",
       "      <td>1089.000000</td>\n",
       "      <td>0.199406</td>\n",
       "      <td>127883.000000</td>\n",
       "      <td>4.321727</td>\n",
       "      <td>332.274390</td>\n",
       "      <td>50.450000</td>\n",
       "      <td>36.230000</td>\n",
       "      <td>9.780550</td>\n",
       "      <td>40716.025941</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "              Year        Revenue       Expenses    Investment    Customers  \\\n",
       "count   100.000000     100.000000     100.000000    100.000000   100.000000   \n",
       "mean   2022.980000  208287.300000  159062.100000  52077.030000  1001.370000   \n",
       "std       0.803779   45363.869918   36615.183976  14959.048863    30.968102   \n",
       "min    2022.000000  110575.000000   85825.000000  13216.000000   919.000000   \n",
       "25%    2022.000000  176619.750000  131637.500000  43515.000000   979.000000   \n",
       "50%    2023.000000  207772.000000  160973.500000  53473.500000  1000.000000   \n",
       "75%    2024.000000  243601.750000  185880.500000  62878.750000  1024.000000   \n",
       "max    2024.000000  336721.000000  257380.000000  84136.000000  1089.000000   \n",
       "\n",
       "       ConversionRate         Profit         ROI  RevenuePerCustomer  \\\n",
       "count       90.000000     100.000000  100.000000          100.000000   \n",
       "mean         0.106458   49225.200000    1.061028          208.280924   \n",
       "std          0.055854   26484.609076    0.805744           46.171606   \n",
       "min          0.010880    9157.000000    0.130130          105.510496   \n",
       "25%          0.054472   27930.250000    0.595550          176.025604   \n",
       "50%          0.105768   45020.500000    0.859758          202.093757   \n",
       "75%          0.152207   66727.750000    1.293277          242.041613   \n",
       "max          0.199406  127883.000000    4.321727          332.274390   \n",
       "\n",
       "         Latitude   Longitude  MarketGrowth      AdBudget  \n",
       "count  100.000000  100.000000    100.000000    100.000000  \n",
       "mean    49.384300   30.876300      4.995655  29534.088215  \n",
       "std      1.430864    4.663345      1.665239   5252.362788  \n",
       "min     46.480000   24.020000      1.315110  13179.522368  \n",
       "25%     49.830000   28.895000      3.938343  26088.799167  \n",
       "50%     49.990000   30.730000      4.921285  29232.128695  \n",
       "75%     49.990000   36.230000      6.156511  33816.318723  \n",
       "max     50.450000   36.230000      9.780550  40716.025941  "
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df.describe()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {
    "id": "I2RIfHwU5EYh"
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Company\n",
      "Company\n",
      "False    100\n",
      "Name: count, dtype: int64\n",
      "\n",
      "Year\n",
      "Year\n",
      "False    100\n",
      "Name: count, dtype: int64\n",
      "\n",
      "Region\n",
      "Region\n",
      "False    100\n",
      "Name: count, dtype: int64\n",
      "\n",
      "Industry\n",
      "Industry\n",
      "False    100\n",
      "Name: count, dtype: int64\n",
      "\n",
      "Revenue\n",
      "Revenue\n",
      "False    100\n",
      "Name: count, dtype: int64\n",
      "\n",
      "Expenses\n",
      "Expenses\n",
      "False    100\n",
      "Name: count, dtype: int64\n",
      "\n",
      "Investment\n",
      "Investment\n",
      "False    100\n",
      "Name: count, dtype: int64\n",
      "\n",
      "Customers\n",
      "Customers\n",
      "False    100\n",
      "Name: count, dtype: int64\n",
      "\n",
      "ConversionRate\n",
      "ConversionRate\n",
      "False    90\n",
      "True     10\n",
      "Name: count, dtype: int64\n",
      "\n",
      "Profit\n",
      "Profit\n",
      "False    100\n",
      "Name: count, dtype: int64\n",
      "\n",
      "ROI\n",
      "ROI\n",
      "False    100\n",
      "Name: count, dtype: int64\n",
      "\n",
      "RevenuePerCustomer\n",
      "RevenuePerCustomer\n",
      "False    100\n",
      "Name: count, dtype: int64\n",
      "\n",
      "Latitude\n",
      "Latitude\n",
      "False    100\n",
      "Name: count, dtype: int64\n",
      "\n",
      "Longitude\n",
      "Longitude\n",
      "False    100\n",
      "Name: count, dtype: int64\n",
      "\n",
      "Scenario\n",
      "Scenario\n",
      "False    100\n",
      "Name: count, dtype: int64\n",
      "\n",
      "MarketGrowth\n",
      "MarketGrowth\n",
      "False    100\n",
      "Name: count, dtype: int64\n",
      "\n",
      "AdBudget\n",
      "AdBudget\n",
      "False    100\n",
      "Name: count, dtype: int64\n",
      "\n"
     ]
    }
   ],
   "source": [
    "missing_data = df.isnull()\n",
    "for column in missing_data.columns.values.tolist():\n",
    "    print(column)\n",
    "    print (missing_data[column].value_counts())\n",
    "    print(\"\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "id": "liQNKZPD9OkD"
   },
   "source": [
    "## __Конфігурація сторінки__\n",
    "\n",
    "\n",
    "Визначимо налаштування програми, надавши їй заголовок сторінки та значок, які відображаються в браузері. Це також визначає вміст сторінки, який буде відображатися в широкому макеті, який вписується в ширину сторінки, а також відображає бічну панель у розгорнутому стані.\n",
    "\n",
    "`st.set_page_config(...)` у Streamlit — задає загальні параметри зовнішнього вигляду сторінки Streamlit-додатку. Її потрібно викликати одразу після імпорту `streamlit`, до будь-якого іншого коду Streamlit.\n",
    "\n",
    "___Синтаксис:___\n",
    "\n",
    "```python\n",
    "st.set_page_config(\n",
    "    page_title=None,\n",
    "    page_icon=None,\n",
    "    layout=\"centered\",\n",
    "    initial_sidebar_state=\"auto\",\n",
    "    menu_items=None\n",
    ")\n",
    "```\n",
    "\n",
    "| Параметр                | Тип      | Опис |\n",
    "|-------------------------|----------|------|\n",
    "| `page_title`            | `str`    | Назва сторінки (відображається у вкладці браузера) |\n",
    "| `page_icon`             | `str` або `Image` | Емодзі або шлях до файлу з іконкою (favicon) |\n",
    "| `layout`                | `str`    | `'centered'` (стандарт) або `'wide'` (повна ширина) |\n",
    "| `initial_sidebar_state` | `str`    | `'auto'`, `'expanded'`, `'collapsed'` — як відкривається бокове меню |\n",
    "| `menu_items`            | `dict`   | Налаштування меню у правому верхньому куті: `{ 'Get Help', 'Report a bug', 'About' }` |\n",
    "\n",
    "\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {
    "id": "bq3kYYSJFRqA"
   },
   "outputs": [],
   "source": [
    "st.set_page_config(\n",
    "    page_title=\"Економічний дашборд\",\n",
    "    page_icon=\"📊\",\n",
    "    layout=\"wide\",\n",
    "    initial_sidebar_state=\"expanded\",\n",
    "    menu_items={\n",
    "        'Get Help': 'https://docs.streamlit.io/',\n",
    "        'Report a bug': 'https://github.com/streamlit/streamlit/issues',\n",
    "        'About': 'Інтерактивна панель для економічного аналізу підприємств'\n",
    "    }\n",
    ")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "id": "5cgjLc2Wey0b"
   },
   "source": [
    "## __Бічна панель (**`st.sidebar`**)__\n",
    "\n",
    "у Streamlit — це окрема область інтерфейсу, яка розташовується ліворуч і використовується для фільтрів, параметрів, налаштувань, навігації.\n",
    "\n",
    "Вона дозволяє розділити логіку:\n",
    "- зліва — керування\n",
    "- справа — результати, графіки, аналітика\n",
    "\n",
    "\n",
    "| Компонент   `sidebar`            | Опис                                              |\n",
    "|-------------------------|---------------------------------------------------|\n",
    "| `st.sidebar.title()`    | Заголовок                                         |\n",
    "| `st.sidebar.markdown()` | Текстовий опис / інструкції                       |\n",
    "| `st.sidebar.selectbox()`| Один вибір зі списку                              |\n",
    "| `st.sidebar.multiselect()`| Кілька виборів                                   |\n",
    "| `st.sidebar.slider()`   | Слайдер для чисел або дат                         |\n",
    "| `st.sidebar.radio()`    | Вибір одного варіанту з декількох (радіо-кнопки)  |\n",
    "| `st.sidebar.checkbox()` | Прапорець                                |\n",
    "| `st.sidebar.file_uploader()` | Завантаження CSV, Excel, зображень             |\n",
    "| `st.sidebar.button()`   | Кнопка, яка реагує на клік                        |\n",
    "| `st.sidebar.info()` / `warning()` | Інформаційні повідомлення         |\n",
    "\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "id": "_wviotgMolHt"
   },
   "source": [
    "## __Створимо наступну бічну панель (`st.sidebar`):__\n",
    "\n",
    "```python\n",
    "st.sidebar.title(\"Панель фільтрації\")\n",
    "```\n",
    "> Створює заголовок в лівій боковій панелі\n",
    "\n",
    "***Фільтри:***\n",
    "\n",
    "```python\n",
    "st.sidebar.selectbox(\"Рік\", sorted(df[\"Year\"].unique()))\n",
    "```\n",
    "> Випадаючий список із доступних років  \n",
    "Користувач обирає один рік для фільтрації.\n",
    "\n",
    "\n",
    "```python\n",
    "st.sidebar.multiselect(\"Регіон\", df[\"Region\"].unique(), default=df[\"Region\"].unique())\n",
    "```\n",
    "> Список із можливістю вибору декількох регіонів. По замовчуванню обрані всі регіони.\n",
    "\n",
    "\n",
    "```python\n",
    "st.sidebar.multiselect(\"Галузь\", df[\"Industry\"].unique(), default=df[\"Industry\"].unique())\n",
    "```\n",
    "> Вибір однієї або кількох галузей. По замовчуванню обрані всі галузі.\n",
    "\n",
    "\n",
    "```python\n",
    "st.sidebar.radio(\"Сценарій\", df[\"Scenario\"].unique())\n",
    "```\n",
    "> Вибір одного варіанту зі сценаріїв розвитку подій (наприклад: Optimistic, Baseline, Pessimistic)\n",
    "\n",
    "\n",
    "```python\n",
    "st.sidebar.slider(\n",
    "    \"Максимальний рекламний бюджет\",\n",
    "    min_value=int(df[\"AdBudget\"].min()),\n",
    "    max_value=int(df[\"AdBudget\"].max()),\n",
    "    value=int(df[\"AdBudget\"].max()),\n",
    "    step=1000\n",
    ")\n",
    "```\n",
    "> Слайдер, який дозволяє обмежити максимальний рекламний бюджет\n",
    "\n",
    "\n",
    "***Чекбокс***\n",
    "\n",
    "```python\n",
    "show_map = st.sidebar.checkbox(\"🗺 Показати мапу компаній\")\n",
    "```\n",
    "> Дозволяє увімкнути або вимкнути мапу на головній панелі.\n",
    "\n",
    "\n",
    "\n",
    "***Перемикач типу графіка***\n",
    "\n",
    "```python\n",
    "chart_option = st.sidebar.radio(\n",
    "    \"Оберіть графік для перегляду:\",\n",
    "    [...]\n",
    ")\n",
    "```\n",
    "\n",
    "Користувач може обрати один із шести графіків:\n",
    "\n",
    "| Варіант                                      | Що показує                                  |\n",
    "|----------------------------------------------|----------------------------------------------|\n",
    "| `Доходи на клієнта vs Витрати`               | Scatter-графік між `Expenses` і `RevenuePerCustomer` |\n",
    "| `Boxplot прибутку по галузях`                | Розподіл прибутку в різних галузях           |\n",
    "| `Scatter: Прибуток vs Інвестиції`            | Залежність прибутку від інвестицій           |\n",
    "| `Гістограма конверсії по галузях`            | Середній рівень `ConversionRate` у галузях   |\n",
    "|`Теплова карта кореляцій`|Візуалізує кореляції між числовими змінними у відфільтрованій таблиці|\n",
    "|`Кластеризація компаній (KMeans)`|Кластеризація за `ROI` та `Investment`|\n",
    "\n",
    "\n",
    "\n",
    "***Інформаційний блок***\n",
    "\n",
    "```python\n",
    "st.sidebar.markdown(\" **Інструкція**: ...\")\n",
    "```\n",
    "> Виводить просту текстову інструкцію, яка допомагає користувачу зрозуміти, як користуватись фільтрами і навігацією. Використовується мова розмітки markdown\n",
    "\n",
    "---\n",
    "\n",
    "\n",
    "Ця бокова панель забезпечує:\n",
    "\n",
    "|  Компонент         | Призначення                        |\n",
    "|----------------------|-------------------------------------|\n",
    "|  Selectbox         | Обрати 1 рік                       |\n",
    "|  Multiselect        | Обрати кілька регіонів/галузей     |\n",
    "|  Radio             | Обрати сценарій і тип графіка      |\n",
    "|  Слайдер           | Обмежити за рекламним бюджетом     |\n",
    "|  Checkbox          | Показати/приховати карту           |\n",
    "|  Markdown          | Надати інструкцію користувачу      |\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {
    "id": "0-MXdvZxGzP4"
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2026-04-25 14:35:51.989 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run C:\\Users\\Yana\\anaconda3\\Lib\\site-packages\\ipykernel_launcher.py [ARGUMENTS]\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "DeltaGenerator(_root_container=1, _parent=DeltaGenerator())"
      ]
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Бічна панель / SIDEBAR\n",
    "st.sidebar.title(\"Панель фільтрації\")\n",
    "\n",
    "# Фільтри\n",
    "selected_year = st.sidebar.selectbox(\"Рік\", sorted(df[\"Year\"].unique()))\n",
    "selected_region = st.sidebar.multiselect(\"Регіон\", df[\"Region\"].unique(), default=df[\"Region\"].unique())\n",
    "selected_industry = st.sidebar.multiselect(\"Галузь\", df[\"Industry\"].unique(), default=df[\"Industry\"].unique())\n",
    "selected_scenario = st.sidebar.radio(\"Сценарій\", df[\"Scenario\"].unique())\n",
    "\n",
    "selected_max_adbudget = st.sidebar.slider(\n",
    "    \"Максимальний рекламний бюджет\",\n",
    "    min_value=int(df[\"AdBudget\"].min()),\n",
    "    max_value=int(df[\"AdBudget\"].max()),\n",
    "    value=int(df[\"AdBudget\"].max()),\n",
    "    step=1000\n",
    ")\n",
    "\n",
    "# Чекбокси для відображення\n",
    "show_map = st.sidebar.checkbox(\"🗺 Показати карту компаній\")\n",
    "\n",
    "# Перемикач графіків\n",
    "chart_option = st.sidebar.radio(\n",
    "    \"📈 Оберіть графік для перегляду:\",\n",
    "    [\n",
    "        \"Доходи на клієнта vs Витрати\",\n",
    "        \"Boxplot прибутку по галузях\",\n",
    "        \"Scatter: Прибуток vs Інвестиції\",\n",
    "        \"Гістограма конверсії по галузях\",\n",
    "        \"Теплова карта кореляцій\",\n",
    "        \"Кластеризація компаній (KMeans)\"\n",
    "    ]\n",
    ")\n",
    "\n",
    "# Інформаційний блок\n",
    "st.sidebar.markdown(\"---\")\n",
    "st.sidebar.markdown(\" **Інструкція**: \\nФільтруйте дані за параметрами і переглядайте графіки та таблиці на панелі праворуч.\")\n",
    "st.sidebar.markdown(\" **Автор**: Lazar_Iryna\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "id": "IoLsxIdlqbE_"
   },
   "source": [
    "## __Фільтрація__\n",
    "\n",
    "\n",
    "Цей блок фільтрує основний DataFrame `df` відповідно до вибору користувача в бічній панелі (`sidebar`). Результат зберігається у змінну `df_filtered`, яка використовується далі для побудови таблиці, графіків, завантаження CSV тощо.\n",
    "\n",
    " `df[...]`  \n",
    "Це підмножина початкового датафрейму — тут передається логічна маска, що вибирає лише ті рядки, які відповідають критеріям.\n",
    "\n",
    "`(df[\"Year\"] == selected_year)`  \n",
    "Фільтрує лише ті записи, у яких значення в колонці `Year` дорівнює вибраному року.\n",
    "\n",
    "`(df[\"Region\"].isin(selected_region))`  \n",
    "Залишає лише ті рядки, де `Region` міститься у списку вибраних регіонів.  \n",
    "Функція `.isin()` перевіряє, чи є значення у списку.\n",
    "\n",
    "`(df[\"Industry\"].isin(selected_industry))`  \n",
    "Залишає лише ті записи, де `Industry` відповідає вибраним галузям.\n",
    "\n",
    "`(df[\"Scenario\"] == selected_scenario)`  \n",
    "Фільтрує за вибраним сценарієм.\n",
    "\n",
    "`(df[\"AdBudget\"] <= selected_max_adbudget)`  \n",
    "Обмежує вибір рядків лише тими, де рекламний бюджет не перевищує вказане максимальне значення зі слайдера.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {
    "id": "DiK8iJwmqart"
   },
   "outputs": [],
   "source": [
    "# Фільтрація\n",
    "\n",
    "df_filtered = df[\n",
    "    (df[\"Year\"] == selected_year) &\n",
    "    (df[\"Region\"].isin(selected_region)) &\n",
    "    (df[\"Industry\"].isin(selected_industry)) &\n",
    "    (df[\"Scenario\"] == selected_scenario) &\n",
    "    (df[\"AdBudget\"] <= selected_max_adbudget)\n",
    "]\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "id": "d5BlygixBZaJ"
   },
   "source": [
    "## __Побудова моделі лінійної регресії__\n",
    "\n",
    "\n",
    "***Блок регресії в бічній панелі***\n",
    "\n",
    "`numeric_columns`: отримує список усіх числових стовпців з відфільтрованого DataFrame `df_filtered`, тому цей блок треба писати після створення відфільтрованого `df_filtered`.\n",
    "\n",
    "`reg_x` та `reg_y`: дозволяють користувачу вибрати незалежну (X) та залежну (Y) змінні для побудови регресії.\n",
    "\n",
    "`show_regression`: чекбокс, який визначає, чи слід відображати регресійну модель.\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {
    "id": "3tKY-O6dKATm"
   },
   "outputs": [],
   "source": [
    "# Блок регресії\n",
    "st.sidebar.markdown(\"Побудова регресії\")\n",
    "numeric_columns = df_filtered.select_dtypes(include=np.number).columns.tolist()\n",
    "\n",
    "reg_x = st.sidebar.selectbox(\"Оберіть змінну X\", numeric_columns, index=0)\n",
    "reg_y = st.sidebar.selectbox(\"Оберіть змінну Y\", numeric_columns, index=1)\n",
    "show_regression = st.sidebar.checkbox(\"Показати регресійну модель\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "id": "NWi-bae6ze9S"
   },
   "source": [
    "## __Основна панель Streamlit-додатку__\n",
    "\n",
    "Основна панель Streamlit-додатку формує фінальний вигляд і поведінку сторінки після фільтрації\n",
    "\n",
    "\n",
    "***Заголовок і кількість компаній***\n",
    "\n",
    "```python\n",
    "st.title(\"📊 Економічний дашборд компаній\")\n",
    "st.subheader(f\"🔍 Відфільтровано {df_filtered.shape[0]} компаній\")\n",
    "```\n",
    "\n",
    "`st.title(...)` — основний заголовок сторінки.\n",
    "\n",
    "`st.subheader(...)` — повідомляє користувачу, скільки компаній залишилось після застосування фільтрів.\n",
    "\n",
    "`df_filtered.shape[0]` — кількість рядків (компаній) у відфільтрованому DataFrame.\n",
    "\n",
    "\n",
    "___Кнопка завантаження CSV___\n",
    "\n",
    "```python\n",
    "csv = df_filtered.to_csv(index=False).encode(\"utf-8\")\n",
    "st.download_button(\n",
    "    label=\"⬇️ Завантажити CSV\",\n",
    "    data=csv,\n",
    "    file_name=\"filtered_companies.csv\",\n",
    "    mime=\"text/csv\"\n",
    ")\n",
    "```\n",
    "\n",
    "> Конвертує таблицю в CSV і кодує її для завантаження.\n",
    "\n",
    "`st.download_button(...)` — додає інтерактивну кнопку, щоб користувач міг завантажити дані.\n",
    "\n",
    "___Таблиця результатів___\n",
    "\n",
    "\n",
    "> Виводить повну таблицю результатів у вигляді інтерактивної таблиці з прокруткою, сортуванням тощо.\n",
    "\n",
    "**`all_columns`**: отримує список усіх стовпців у відфільтрованому DataFrame `df_filtered`.\n",
    "\n",
    "**`default_columns`**: визначає список стовпців, які будуть вибрані за замовчуванням, якщо вони присутні в `df_filtered`.\n",
    "\n",
    "**`st.multiselect`**: створює віджет для вибору кількох стовпців, дозволяючи користувачам обрати, які стовпці відображати.\n",
    "\n",
    "**`st.dataframe`**: відображає таблицю з обраними стовпцями.\n",
    "\n",
    "**`st.info`**: виводить повідомлення, якщо не вибрано жодного стовпця.\n",
    "\n",
    "\n",
    "___🗺 Карта компаній___\n",
    "\n",
    "```python\n",
    "if show_map:\n",
    "    st.subheader(\"🗺 Географія компаній\")\n",
    "\n",
    "    map_data = df_filtered[[\"Latitude\", \"Longitude\"]].dropna().rename(\n",
    "        columns={\"Latitude\": \"latitude\", \"Longitude\": \"longitude\"}\n",
    "    )\n",
    "\n",
    "    if not map_data.empty:\n",
    "        st.map(map_data)\n",
    "    else:\n",
    "        st.warning(\"Немає доступних координат для побудови карти.\")\n",
    "```\n",
    "\n",
    "`show_map` — логічна змінна (встановлюється через чекбокс у sidebar).\n",
    "\n",
    "`dropna()` — виключає компанії без координат.\n",
    "\n",
    "`rename(...)` — перетворює назви колонок у формат, який вимагає `st.map()` (все маленькими).\n",
    "\n",
    "`st.map(...)` — будує інтерактивну карту.\n",
    "\n",
    "___Графіки за вибором користувача___\n",
    "\n",
    "> Залежно від `chart_option`, виводиться певний графік (визначається через `radio` у sidebar):\n",
    "\n",
    "1. __Доходи на клієнта vs Витрати (Altair)__\n",
    "\n",
    "> компанія, вісь X: `Expenses`, Y: `RevenuePerCustomer`.\n",
    "\n",
    "2. __Boxplot прибутку по галузях (Seaborn)__\n",
    "\n",
    "> Дозволяє виявити галузі з високою/низькою волатильністю.\n",
    "\n",
    "3. __Scatter-графік: Прибуток vs Інвестиції (Altair)__\n",
    "\n",
    "> Візуалізує залежність між розміром інвестицій та прибутком.\n",
    "\n",
    "4. __Гістограма конверсії по галузях (Seaborn)__\n",
    "\n",
    "> Стовпчиковий графік із середнім `ConversionRate` для кожної галузі.\n",
    "\n",
    "5. __Теплова карта кореляцій (Seaborn Heatmap)__\n",
    "\n",
    "```python\n",
    "numeric_cols = df_filtered.select_dtypes(include=[np.number])\n",
    "corr = numeric_cols.corr()\n",
    "```\n",
    "\n",
    "> Обчислює кореляцію між усіма числовими змінними. Показує, які показники мають сильну/слабку кореляцію.\n",
    "\n",
    "6. __Кластеризація компаній (KMeans)__\n",
    "\n",
    "```python\n",
    "cluster_data = df_filtered[[\"ROI\", \"Investment\"]].dropna()\n",
    "kmeans = KMeans(n_clusters=3).fit(...)\n",
    "```\n",
    "\n",
    "> Використовується KMeans для розбиття компаній на 3 кластери за ознаками `ROI` та `Investment`. Кожна точка має колір відповідно до кластера.\n",
    "\n",
    "_Працює лише якщо є мінімум 3 компанії з непорожніми значеннями._\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {
    "id": "hjUurC4Ynx-S"
   },
   "outputs": [],
   "source": [
    "# Основна панель\n",
    "st.title(\"📊 Економічний дашборд компаній\")\n",
    "st.subheader(f\"🔍 Відфільтровано {df_filtered.shape[0]} компаній\")\n",
    "\n",
    "# Кнопка завантаження CSV\n",
    "csv = df_filtered.to_csv(index=False).encode(\"utf-8\")\n",
    "st.download_button(\n",
    "    label=\"⬇️ Завантажити CSV\",\n",
    "    data=csv,\n",
    "    file_name=\"filtered_companies.csv\",\n",
    "    mime=\"text/csv\"\n",
    ")\n",
    "\n",
    "# Інтерактивна таблиця результатів\n",
    "st.subheader(\"Оберіть, які стовпці таблиці відображати\")\n",
    "\n",
    "all_columns = df_filtered.columns.tolist()\n",
    "default_columns = [\"Company\", \"Region\", \"Industry\", \"Profit\", \"ROI\"]\n",
    "\n",
    "selected_columns = st.multiselect(\n",
    "    \"Оберіть стовпці для перегляду\",\n",
    "    options=all_columns,\n",
    "    default=[col for col in default_columns if col in all_columns]\n",
    ")\n",
    "\n",
    "if selected_columns:\n",
    "    st.dataframe(df_filtered[selected_columns])\n",
    "else:\n",
    "    st.info(\"Оберіть хоча б один стовпець, щоб побачити таблицю.\")\n",
    "\n",
    "# Карта компаній\n",
    "if show_map:\n",
    "    st.subheader(\"🗺 Географія компаній\")\n",
    "\n",
    "    map_data = df_filtered[[\"Latitude\", \"Longitude\"]].dropna().rename(\n",
    "        columns={\"Latitude\": \"latitude\", \"Longitude\": \"longitude\"}\n",
    "    )\n",
    "\n",
    "    if not map_data.empty:\n",
    "        st.map(map_data)\n",
    "    else:\n",
    "        st.warning(\"Немає доступних координат для побудови карти.\")\n",
    "\n",
    "# Відображення обраного графіка\n",
    "if chart_option == \"Доходи на клієнта vs Витрати\":\n",
    "    st.subheader(\"📊 Доходи на клієнта vs Витрати\")\n",
    "    chart = alt.Chart(df_filtered).mark_circle(size=60).encode(\n",
    "        x=\"Expenses:Q\",\n",
    "        y=\"RevenuePerCustomer:Q\",\n",
    "        color=\"Industry:N\",\n",
    "        tooltip=[\"Company\", \"Expenses\", \"RevenuePerCustomer\", \"Industry\"]\n",
    "    ).interactive().properties(title=\"Дохід на клієнта vs Витрати\")\n",
    "    st.altair_chart(chart, use_container_width=True)\n",
    "\n",
    "elif chart_option == \"Boxplot прибутку по галузях\":\n",
    "    st.subheader(\"📊 Boxplot прибутку по галузях\")\n",
    "    fig, ax = plt.subplots(figsize=(10, 5))\n",
    "    sns.boxplot(data=df_filtered, x=\"Industry\", y=\"Profit\", ax=ax)\n",
    "    ax.set_title(\"Розподіл прибутку по галузях\")\n",
    "    st.pyplot(fig)\n",
    "\n",
    "elif chart_option == \"Scatter: Прибуток vs Інвестиції\":\n",
    "    st.subheader(\"📊 Scatter: Прибуток vs Інвестиції\")\n",
    "    chart = alt.Chart(df_filtered).mark_circle(size=60).encode(\n",
    "        x=\"Investment:Q\",\n",
    "        y=\"Profit:Q\",\n",
    "        color=\"Industry:N\",\n",
    "        tooltip=[\"Company\", \"Investment\", \"Profit\"]\n",
    "    ).interactive().properties(title=\"Прибуток vs Інвестиції\")\n",
    "    st.altair_chart(chart, use_container_width=True)\n",
    "\n",
    "elif chart_option == \"Гістограма конверсії по галузях\":\n",
    "    st.subheader(\"📊 Гістограма конверсії по галузях\")\n",
    "    fig, ax = plt.subplots(figsize=(10, 5))\n",
    "    sns.barplot(\n",
    "        data=df_filtered,\n",
    "        x=\"Industry\",\n",
    "        y=\"ConversionRate\",\n",
    "        estimator=\"mean\",\n",
    "        ax=ax\n",
    "    )\n",
    "    ax.set_title(\"Середній Conversion Rate по галузях\")\n",
    "    st.pyplot(fig)\n",
    "\n",
    "elif chart_option == \"Теплова карта кореляцій\":\n",
    "    st.subheader(\"📊 Теплова карта кореляцій\")\n",
    "    numeric_cols = df_filtered.select_dtypes(include=[np.number])\n",
    "    corr = numeric_cols.corr()\n",
    "    fig, ax = plt.subplots(figsize=(10, 6))\n",
    "    sns.heatmap(corr, annot=True, cmap=\"coolwarm\", fmt=\".2f\", ax=ax)\n",
    "    ax.set_title(\"Кореляційна матриця числових показників\")\n",
    "    st.pyplot(fig)\n",
    "\n",
    "elif chart_option == \"Кластеризація компаній (KMeans)\":\n",
    "    st.subheader(\"📊 Кластеризація компаній на основі ROI та Investment\")\n",
    "    cluster_data = df_filtered[[\"ROI\", \"Investment\"]].dropna().copy()\n",
    "\n",
    "    if cluster_data.shape[0] >= 3:\n",
    "        kmeans = KMeans(n_clusters=3, random_state=0)\n",
    "        cluster_data[\"Cluster\"] = kmeans.fit_predict(cluster_data)\n",
    "\n",
    "        chart = alt.Chart(cluster_data).mark_circle(size=60).encode(\n",
    "            x=\"Investment:Q\",\n",
    "            y=\"ROI:Q\",\n",
    "            color=\"Cluster:N\",\n",
    "            tooltip=[\"ROI\", \"Investment\", \"Cluster\"]\n",
    "        ).interactive().properties(title=\"Кластеризація за ROI та Investment\")\n",
    "        st.altair_chart(chart, use_container_width=True)\n",
    "    else:\n",
    "        st.warning(\"Недостатньо даних для кластеризації (потрібно ≥ 3 рядки).\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "id": "ltXufxdx1nsm"
   },
   "source": [
    "## __Реалізація моделі лінійної регресії__\n",
    "\n",
    "- Перевіряється, чи активовано чекбокс `show_regression`.\n",
    "- Створюється новий DataFrame `df_reg`, що містить лише вибрані змінні X та Y, з видаленими пропущеними значеннями.\n",
    "- Якщо в `df_reg` є принаймні 2 рядки, будується лінійна регресійна модель за допомогою `LinearRegression` з бібліотеки `scikit-learn`.\n",
    "- Виводяться коефіцієнт нахилу $\\beta$, зсув `intercept` та коефіцієнт детермінації $R^2$.\n",
    "- Будується графік розсіювання з лінією регресії.\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {
    "id": "4KbgaUsQJ0wp"
   },
   "outputs": [],
   "source": [
    "# Побудова регресійної моделі\n",
    "if show_regression:\n",
    "    st.subheader(f\"📈 Лінійна регресія: {reg_y} ~ {reg_x}\")\n",
    "\n",
    "    df_reg = df_filtered[[reg_x, reg_y]].dropna()\n",
    "\n",
    "    if df_reg.shape[0] >= 2:\n",
    "        model = LinearRegression()\n",
    "        model.fit(df_reg[[reg_x]], df_reg[reg_y])\n",
    "        y_pred = model.predict(df_reg[[reg_x]])\n",
    "\n",
    "        coef = model.coef_[0]\n",
    "        intercept = model.intercept_\n",
    "        r2 = model.score(df_reg[[reg_x]], df_reg[reg_y])\n",
    "\n",
    "        st.markdown(f\"**Коефіцієнт нахилу (β):** {coef:.4f}\")\n",
    "        st.markdown(f\"**Зсув (intercept):** {intercept:.4f}\")\n",
    "        st.markdown(f\"**R²:** {r2:.4f}\")\n",
    "\n",
    "        fig, ax = plt.subplots(figsize=(8, 5))\n",
    "        sns.scatterplot(data=df_reg, x=reg_x, y=reg_y, ax=ax)\n",
    "        sns.lineplot(x=df_reg[reg_x], y=y_pred, color='red', ax=ax)\n",
    "        ax.set_title(f\"Регресія {reg_y} ~ {reg_x}\")\n",
    "        st.pyplot(fig)\n",
    "    else:\n",
    "        st.warning(\"Недостатньо даних для побудови регресії.\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "id": "huHRYPaK36l0"
   },
   "source": [
    "##<center>__Самостійні завдання__</center>\n",
    "\n",
    "> Скопіювати блок самостійних завдань в окремий файл ***LastName_DA6.py***\n",
    "\n",
    "> Інсталюйте необхідні пакети бібліотек Python збережіть у файл `requirements.txt`\n",
    "\n",
    "> завантажте файл зі статистичного банку даних, з яким будете працювати `data.csv`"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "id": "jDnw9G5y4Glz"
   },
   "source": [
    "### Завдання\n",
    "\n",
    "1. Створіть dashboard, як додаток у **Streamlit Community Cloud**\n",
    "2. Додаток має містити: панель фільтрації з елементами\n",
    "- Заголовок      \n",
    "- Текстовий опис / інструкції                       \n",
    "- Один вибір зі списку                              \n",
    "- Кілька виборів                                   \n",
    "- Вибір одного варіанту з декількох (радіо-кнопки)  \n",
    "- Прапорець        \n",
    "3. В головній частині: таблиця, як результат фільтрів з можливістю вибору колонок\n",
    "4. Графічне представлення (мінімум 3 типи графіки)\n",
    "5. Реалізація регресійної моделі або інших (кластеризації/класифікації)                        \n",
    "6. Створені файли мають бути розміщені в репрозиторії GitHub, та імплементуватися в Streamlit Community Cloud"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "colab": {
   "provenance": []
  },
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
